import fitz  # PyMuPDF
import os
import sys

# Fix Unicode encoding for Windows console
if sys.platform == 'win32':
    import codecs
    sys.stdout = codecs.getwriter('utf-8')(sys.stdout.buffer, 'strict')
    sys.stderr = codecs.getwriter('utf-8')(sys.stderr.buffer, 'strict')

def extract_pdf_to_study_guide(pdf_path, output_path=None):
    """
    Extracts a PDF page-by-page and generates a lossless study guide.
    
    Args:
        pdf_path: Path to the PDF file
        output_path: Optional output path. If None, creates a .txt file with same name
    """
    
    # Open the PDF
    doc = fitz.open(pdf_path)
    total_pages = len(doc)
    
    # Generate output filename if not provided
    if output_path is None:
        base_name = os.path.splitext(os.path.basename(pdf_path))[0]
        output_path = os.path.join(
            os.path.dirname(pdf_path), 
            f"{base_name}_STUDY_GUIDE.txt"
        )
    
    print(f"📚 Processing: {os.path.basename(pdf_path)}")
    print(f"📄 Total Pages: {total_pages}")
    print(f"💾 Output: {output_path}")
    print("=" * 80)
    
    with open(output_path, "w", encoding="utf-8") as f:
        # Write header
        f.write("=" * 80 + "\n")
        f.write(f"📖 LOSSLESS STUDY GUIDE\n")
        f.write(f"Source: {os.path.basename(pdf_path)}\n")
        f.write(f"Total Pages: {total_pages}\n")
        f.write(f"Generated by: Universal Study Guide System\n")
        f.write("=" * 80 + "\n\n")
        
        # Extract each page
        for page_num in range(total_pages):
            page = doc.load_page(page_num)
            text = page.get_text()
            
            # Write page header
            f.write(f"\n{'='*80}\n")
            f.write(f"📄 PAGE {page_num + 1} of {total_pages}\n")
            f.write(f"{'='*80}\n\n")
            
            # Write content
            if text.strip():
                f.write(text)
            else:
                f.write("⚠️ [This page appears to be blank or image-only]\n")
            
            f.write("\n\n")
            
            # Progress indicator
            if (page_num + 1) % 10 == 0:
                print(f"✅ Processed {page_num + 1}/{total_pages} pages...")
    
    print(f"\n🎉 Complete! Study guide saved to:\n{output_path}")
    print(f"\n💡 Next step: Type 'reload' in your RAG app to index this file.")
    
    return output_path


def process_all_pdfs_in_folder(folder_path):
    """
    Process all PDFs in a given folder.
    """
    pdf_files = [f for f in os.listdir(folder_path) if f.lower().endswith('.pdf')]
    
    if not pdf_files:
        print(f"❌ No PDF files found in {folder_path}")
        return
    
    print(f"📂 Found {len(pdf_files)} PDF file(s)")
    print("=" * 80)
    
    for pdf_file in pdf_files:
        pdf_path = os.path.join(folder_path, pdf_file)
        try:
            extract_pdf_to_study_guide(pdf_path)
            print()
        except Exception as e:
            print(f"❌ Error processing {pdf_file}: {e}")
            print()


if __name__ == "__main__":
    # Default to documents folder
    default_folder = r"c:\Users\sumit\rag app\documents"
    
    if len(sys.argv) > 1:
        # User provided a specific PDF path
        pdf_path = sys.argv[1]
        if os.path.isfile(pdf_path):
            extract_pdf_to_study_guide(pdf_path)
        else:
            print(f"❌ File not found: {pdf_path}")
    else:
        # Process all PDFs in documents folder
        print("🔍 No specific file provided. Processing all PDFs in documents folder...")
        print()
        process_all_pdfs_in_folder(default_folder)
